use std::env;
use std::fs;
use std::path::Path;

/// Env keys copied from the build environment into the desktop binary for the embedded
/// Elixir release child process (Finder / Explorer have no direnv). Debug builds omit this;
/// use direnv or export vars when running `tauri dev` / `make app-dev`.
const OPTIONAL_EMBED_KEYS: &[&str] = &[
    "PROMETHEUS_PUSH_GW_HOST",
    "PROMETHEUS_PUSH_GW_USER",
    "PROMETHEUS_PUSH_GW_PASSWORD",
    "TELEMETRY_PUSH_INTERVAL",
    "LOG_LEVEL",
    "SM_LOCALE",
    "DIRECT_FILE_UPLOAD",
];

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let profile = env::var("PROFILE").unwrap_or_default();
    let dest = Path::new(&out_dir).join("embedded_phx_env.rs");

    let body = if profile == "release" {
        let sk = env::var("SECRET_KEY_BASE").unwrap_or_else(|_| {
            panic!(
                "SECRET_KEY_BASE must be set when compiling a release build (e.g. CI secrets before `cargo tauri build`)."
            )
        });
        let lv = env::var("LV_SIGNING_SALT").unwrap_or_else(|_| {
            panic!(
                "LV_SIGNING_SALT must be set when compiling a release build (e.g. CI secrets before `cargo tauri build`)."
            )
        });

        let mut code = String::from(
            "/// Generated by `build.rs` — do not edit.\n\
             pub fn apply_release_elixir_env(cmd: &mut std::process::Command) {\n",
        );
        push_env_line(&mut code, "SECRET_KEY_BASE", &sk);
        push_env_line(&mut code, "LV_SIGNING_SALT", &lv);

        for key in OPTIONAL_EMBED_KEYS {
            println!("cargo:rerun-if-env-changed={key}");
            if let Ok(val) = env::var(key) {
                if !val.is_empty() {
                    push_env_line(&mut code, key, &val);
                }
            }
        }

        code.push_str("}\n");
        code
    } else {
        "/// Generated by `build.rs` — do not edit.\n\
         pub fn apply_release_elixir_env(_cmd: &mut std::process::Command) {}\n"
            .to_string()
    };

    fs::write(&dest, body).expect("write embedded_phx_env.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=SECRET_KEY_BASE");
    println!("cargo:rerun-if-env-changed=LV_SIGNING_SALT");

    let _ = fs::create_dir_all(std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/rel"));
    tauri_build::build();
}

fn push_env_line(buf: &mut String, key: &str, value: &str) {
    buf.push_str("  cmd.env(");
    buf.push_str(&format!("{:?}", key));
    buf.push_str(", ");
    buf.push_str(&format!("{:?}", value));
    buf.push_str(");\n");
}
