version: "3"
services:

  safarimanager:
    build:
      context: .
      dockerfile: Dockerfile
    image: maxdrift/safarimanager:latest
    environment:
      SECRET_KEY_BASE: MROe0TML1wb/8amRSKJ994MKvIpq3JqLM/FMevNTM2YSEst8NXNkcTSkV/C17DP0
    user: "${UID}:${GID}"
    ports:
      - "4000"
    volumes:
      - ~/.safarimanager:/var/safarimanager
  environment:
    UPLOADS_PATH: /var/safarimanager/uploads
    DATABASE_PATH: /var/safarimanager/db
  nginx:
    image: nginx:latest
    volumes:
      - ./support/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - safarimanager
    ports:
      - "4000:8000"
