version: "3"
services:

  safarimanager:
    build:
      context: .
      dockerfile: Dockerfile
    image: maxdrift/safarimanager:local
    environment:
      SECRET_KEY_BASE: MROe0TML1wb/8amRSKJ994MKvIpq3JqLM/FMevNTM2YSEst8NXNkcTSkV/C17DP0
    ports:
      - "4000"
    volumes:
      - ~/.safarimanager/safarimanager.db:/app/lib/safarimanager-0.1.0/priv/safarimanager.db
      - ~/.safarimanager/safarimanager.db-shm:/app/lib/safarimanager-0.1.0/priv/safarimanager.db-shm
      - ~/.safarimanager/safarimanager.db-wal:/app/lib/safarimanager-0.1.0/priv/safarimanager.db-wal
      - ~/.safarimanager/uploads:/app/lib/safarimanager-0.1.0/priv/uploads
  nginx:
    image: nginx:latest
    volumes:
      - ./support/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - safarimanager
    ports:
      - "4000:8000"
