import Config

# Until checksum-Elixir.ExImageResizer.exs lists all targets, compile the NIF from source (Rust on this build host only).
config :rustler_precompiled, :force_build, ex_image_resizer: true

# Do not print debug messages in production
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :logger, level: :info

config :safarimanager, SMWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
