import Config

# Do not print debug messages in production
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :logger, level: :info

config :safarimanager, SMWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Remote Loki logging is fragile in packaged desktop builds (offline, restarts).
config :safarimanager, :enable_svadilfari_logger, false
