name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  macos:
    # runs-on: macos-latest
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Update Homebrew
        run: |
          brew update --preinstall
          cat /dev/null > .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/vips.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/node.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/yarn.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/dylibbundler.rb" >> .github/brew-formulae
      - name: Configure Homebrew cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/vips--*
            ~/Library/Caches/Homebrew/downloads/*--vips-*
            ~/Library/Caches/Homebrew/node--*
            ~/Library/Caches/Homebrew/downloads/*--node-*
            ~/Library/Caches/Homebrew/yarn--*
            ~/Library/Caches/Homebrew/downloads/*--yarn-*
            ~/Library/Caches/Homebrew/dylibbundler--*
            ~/Library/Caches/Homebrew/downloads/*--dylibbundler-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install vips node yarn dylibbundler
      - name: Cache Mix Deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Cache Bootstrap
        uses: actions/cache@v3
        with:
          path: tmp
          key: ${{ runner.os }}-app-${{ hashFiles('.github/scripts/app/bootstrap_mac.sh') }}
      - name: Bootstrap
        run: bash .github/scripts/app/bootstrap_mac.sh
      # - name: Build the app
      #   run: bash .github/scripts/app/build_mac.sh

  # linux-arm:
  #   name: Build on Raspberry Pi (Elixir ${{ matrix.elixir_version }}, OTP ${{ matrix.otp_version }})
  #   runs-on: self-hosted

  #   strategy:
  #     matrix:
  #       elixir_version: ["1.13.4"]
  #       otp_version: ["24.3"]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # - name: Setup Erlang
  #     #   run: |
  #     #     sudo apt update
  #     #     sudo apt install -y wget libssl-dev ncurses-dev
  #     #     wget http://www.erlang.org/download/otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     tar -xzvf otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     cd otp_src_${{ matrix.otp_version }}/
  #     #     ./configure
  #     #     make
  #     #     sudo make install
  #     #     cd ..
  #     #     rm otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     sudo rm -R otp_src_${{ matrix.otp_version }}/
  #     # - name: Setup Elixir
  #     #   run: |
  #     #     wget https://github.com/elixir-lang/elixir/archive/refs/tags/v${{ matrix.elixir_version }}.tar.gz
  #     #     tar -xzvf v${{ matrix.elixir_version }}.tar.gz
  #     #     cd elixir-${{ matrix.elixir_version }}
  #     #     make
  #     #     sudo make install
  #     - name: Restore deps and _build
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           deps
  #           _build
  #         key: ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles('mix.lock') }}
  #     # - name: Restore plts
  #     #   uses: actions/cache@v2
  #     #   with:
  #     #     path: priv/plts
  #     #     key: ${{ runner.os }}-dialyzer-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
  #     - run: |
  #         mix local.hex --force
  #         mix local.rebar --force
  #     # - run: mix deps.get
  #     # - run: MIX_ENV=prod mix compile
  #     # - run: mix test
  #     # - run: sudo apt install -y yarn
  #     - name: Install Npm
  #       run: sudo apt install -y npm
  #     - name: Install Yarn
  #       run: sudo npm install -g yarn
  #     - name: Install zstd
  #       run: sudo apt install -y zstd
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         cache-dependency-path: assets/yarn.lock
  #     - run: MIX_ENV=prod mix setup
  #     - run: MIX_ENV=prod mix release
  #     - name: Upload release artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: linux-binary
  #         path: _build/prod/rel/safarimanager
