name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  macos:
    # runs-on: macos-latest
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      LV_SIGNING_SALT: ${{ secrets.LV_SIGNING_SALT }}
      PROMETHEUS_PUSH_GW_USER: ${{ secrets.PROMETHEUS_PUSH_GW_USER }}
      PROMETHEUS_PUSH_GW_PASSWORD: ${{ secrets.PROMETHEUS_PUSH_GW_PASSWORD }}
      NOTARIZE_IDENTITY: ${{ secrets.NOTARIZE_IDENTITY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Update Homebrew
        run: |
          brew update --preinstall
          cat /dev/null > .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/asdf.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/vips.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/node.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/yarn.rb" >> .github/brew-formulae
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/dylibbundler.rb" >> .github/brew-formulae
      - name: Configure Homebrew cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/asdf--*
            ~/Library/Caches/Homebrew/downloads/*--asdf-*
            ~/Library/Caches/Homebrew/vips--*
            ~/Library/Caches/Homebrew/downloads/*--vips-*
            ~/Library/Caches/Homebrew/node--*
            ~/Library/Caches/Homebrew/downloads/*--node-*
            ~/Library/Caches/Homebrew/yarn--*
            ~/Library/Caches/Homebrew/downloads/*--yarn-*
            ~/Library/Caches/Homebrew/dylibbundler--*
            ~/Library/Caches/Homebrew/downloads/*--dylibbundler-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install asdf vips node yarn dylibbundler
      - name: Setup asdf
        run: |
          mkdir -p ~/.asdf
          if [ $(grep -c "asdf.sh" ~/.bash_profile) -eq 0 ]
          then
            echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ~/.bash_profile
          fi
      - name: Cache asdf Erlang and Elixir
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: asdf-${{ hashFiles('.tool-versions') }}
      - name: Install Erlang OTP (version from .tool-versions)
        run: |
          asdf plugin add erlang || true
          asdf install erlang
      - name: Install Elixir (version from .tool-versions)
        run: |
          asdf plugin add elixir || true
          asdf install elixir
          asdf reshim elixir
      - name: Cache Mix Deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Build the app
        run: |
          pwd
          asdf current
          .github/scripts/app/build_mac.sh
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision

  # linux-arm:
  #   name: Build on Raspberry Pi (Elixir ${{ matrix.elixir_version }}, OTP ${{ matrix.otp_version }})
  #   runs-on: self-hosted

  #   strategy:
  #     matrix:
  #       elixir_version: ["1.13.4"]
  #       otp_version: ["24.3"]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # - name: Setup Erlang
  #     #   run: |
  #     #     sudo apt update
  #     #     sudo apt install -y wget libssl-dev ncurses-dev
  #     #     wget http://www.erlang.org/download/otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     tar -xzvf otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     cd otp_src_${{ matrix.otp_version }}/
  #     #     ./configure
  #     #     make
  #     #     sudo make install
  #     #     cd ..
  #     #     rm otp_src_${{ matrix.otp_version }}.tar.gz
  #     #     sudo rm -R otp_src_${{ matrix.otp_version }}/
  #     # - name: Setup Elixir
  #     #   run: |
  #     #     wget https://github.com/elixir-lang/elixir/archive/refs/tags/v${{ matrix.elixir_version }}.tar.gz
  #     #     tar -xzvf v${{ matrix.elixir_version }}.tar.gz
  #     #     cd elixir-${{ matrix.elixir_version }}
  #     #     make
  #     #     sudo make install
  #     - name: Restore deps and _build
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           deps
  #           _build
  #         key: ${{ runner.os }}-mix-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles('mix.lock') }}
  #     # - name: Restore plts
  #     #   uses: actions/cache@v2
  #     #   with:
  #     #     path: priv/plts
  #     #     key: ${{ runner.os }}-dialyzer-${{ matrix.elixir_version }}-${{ matrix.otp_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
  #     - run: |
  #         mix local.hex --force
  #         mix local.rebar --force
  #     # - run: mix deps.get
  #     # - run: MIX_ENV=prod mix compile
  #     # - run: mix test
  #     # - run: sudo apt install -y yarn
  #     - name: Install Npm
  #       run: sudo apt install -y npm
  #     - name: Install Yarn
  #       run: sudo npm install -g yarn
  #     - name: Install zstd
  #       run: sudo apt install -y zstd
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         cache-dependency-path: assets/yarn.lock
  #     - run: MIX_ENV=prod mix setup
  #     - run: MIX_ENV=prod mix release
  #     - name: Upload release artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: linux-binary
  #         path: _build/prod/rel/safarimanager
